server: 
    port: 3344
spring: 
    application: 
        name: microservicecloud-config
    cloud: 
        config: 
            server: 
                git: 
                     uri: https://github.com/gitking/microservicecloud-config.git #Github上面的git仓库名字
                     force-pull: true
                     username: yale268sh@163.com
                     password: PINGANKUAILE6.=-
                default-label: main
                     